# Generated by Django 5.1.7 on 2025-03-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
