# Generated by Django 5.1.7 on 2025-03-10 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_article_external_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='external_link',
        ),
        migrations.AddField(
            model_name='article',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_articles', to='content.category'),
        ),
    ]
