# Generated by Django 5.1.7 on 2025-03-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_article_cover_design_article_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_design',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
